#!/bin/bash -l

#SBATCH --account=2017-11-25

#SBATCH -J dna

#SBATCH -t 00:15:00

##SBATCH --constraint=[group-0|group-1|group-2|group-3|group-4]

# On Beskow: 2 cpus x 16 cores (+hyperthreading) = 32 (x 2) 
#SBATCH -N 1
#SBATCH -n 32
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1

# MPICH
export MPICH_GNI_MAX_EAGER_MSG_SIZE=131072

# Environment settings
module add  gromacs/2018.1

grompp_opts="-maxwarn 1"

# gmx binaries
gmx_mpi=gmx_mpi
gmx=gmx_seq

# Sequence of runs, depending on each other. Find which stage we are at and continue
# running from there.
groout="confout.gro";
gro="conf.gro"
for current in "em" "equil" "dihedral-6-17"; do   
    # Find the first run that isn't done, i.e.
    # does not have final gro file
    if [ -f "${groout}" ]; then
        # use for input at next dependent stage
	gro=`readlink -f $groout`
	continue
    else
	# run at this stage
	break
    fi	
done

# Get ready to run at this stage.
# Set up the run directory if it doesn't exist already
data="${current}/data"
template="${current}/template"
[ ! -d $data ] && cp -r $template $data

cd $data

# Make a tpr file if there isn't one already
if [ ! -f "$tpr" ]; then	
    mdp="grompp.mdp"
    ndx="index.ndx"
    ndxflag=""
    [ -e "$ndx" ] && ndxflag="-n"
    echo "---> grompp at stage $current"
    $gmx grompp $ndxflag -c $gro -f $mdp $grompp_opts -o $tpr &> grompp.log || exit 1
fi

# Start/continue mdrun. 

# aprun settings
aprun_opts="-cc none"

cont_opts="-cpi -maxh 0.25" # NOTE: -maxh should correspond to the allocated time
if [ "${current}" == "em" ]; then
    mdrun="$gmx_mpi mdrun -v $cont_opts"
    aprun_opts+="  -n 1 -N 1 "
else
    npme=2; nstlist=40; dlb=no; ntomp=2; #-ddorder pp_pme"
    std_opts="-pin on -quiet -v -stepout 10000 -nstlist ${nstlist} -dlb ${dlb} -npme ${npme} -ntomp ${ntomp}" 

    mdrun="$gmx_mpi mdrun $std_opts $cont_opts"
    aprun_opts+=" -n $SLURM_NTASKS -N $SLURM_NTASKS_PER_NODE "
fi

echo "---> mdrun at stage $current"
echo "---> aprun $aprun_opts $mdrun"
aprun $aprun_opts $mdrun

# If the run was short, we just exit earlier than we had to.
echo "---> Reached end of run script."